class PrivacyPolicyTextos
{
  static const FIRSTTEXT = "This privacy policy has been compiled to better serve those who are concerned with how their ‘Personally Identifiable Information’ (PII) is being used online. PII, as described in US privacy law and information security, is information that can be used on its own or with other information to identify, contact, or locate a single person, or to identify an individual in context.\n\nPlease read our privacy policy carefully to get a clear understanding of how we collect, use, protect or otherwise handle your Personally Identifiable Information in accordance ";
  static const WHAT_PERSONAL = "When registering, you may be asked to enter your mailing address or other details to help you with your experience.";
  static const WHEN_DO = "We collect information from you when you subscribe to a newsletter or enter information on our site.";
  static const HOW_DO = "We may use the information we collect from you when you register, make a purchase, sign up for our newsletter, respond to a survey or marketing communication, surf the website, or use certain other site features in the following ways:";
  static const TO_SEND = "To send periodic emails regarding your order or other products and services.";
  static const HOWPROTECTINFO_WE_DO_NOT = "We do not use vulnerability scanning and/or scanning to PCI standards.";
  static const HOWPROTECTINFO_WE_ONLY = "We only provide articles and information. We never ask for credit card numbers.";
  static const HOWPROTECTINFO_WE_USE = "We use regular Malware Scanning.";
  static const HOWPROTECTINFO_YOURPERSONAL = "Your personal information is contained behind secured networks and is only accessible by a limited number of persons who have special access rights to such systems, and are required to keep the information confidential. In addition, all sensitive/credit information you supply is encrypted via Secure Socket Layer (SSL) technology.";
  static const HOWPROTECTINFO_WEIMPLEMENT = "We implement a variety of security measures when a user enters, submits, or accesses their information to maintain the safety of your personal information.";
  static const COOKIES_YES_DOT = "Yes. Cookies are small files that a site or its service provider transfers to your computer’s hard drive through your Web browser (if you allow) that enables the site’s or service provider’s systems to recognize your browser and capture and remember certain information. For instance, we use cookies to help us remember and process the items in your shopping cart. They are also used to help us understand your preferences based on previous or current site activity, which enables us to provide you with improved services. We also use cookies to help us compile aggregate data about site traffic and site interaction so that we can offer better site experiences and tools in the future.\nWe use cookies to:";
  static const COOKIES_UNDERSTAND = "Understand and save user’s preferences for future visits.";
  static const COOKIES_KEEP_TRACK = "Keep track of advertisements.";
  static const COOKIES_YOU_CAN = "You can choose to have your computer warn you each time a cookie is being sent, or you can choose to turn off all cookies. You do this through your browser settings. Since browser is a little different, look at your browser’s Help Menu to learn the correct way to modify your cookies.\n\nIf users disable cookies in their browser:\nIf you turn cookies off, Some of the features that make your site experience more efficient may not function properly.Some of the features that make your site experience more efficient and may not function properly.";
  static const THIRDPARTY_WE_DO = "We do not sell, trade, or otherwise transfer to outside parties your Personally Identifiable Information.";
  static const GOOGLE_GOOGLES = "Google’s advertising requirements can be summed up by Google’s Advertising Principles. They are put in place to provide a positive experience for users.";
  static const GOOGLE_WE_USE = "We use Google AdSense Advertising on our website.Google, as a third-party vendor, uses cookies to serve ads on our site. Google’s use of the DART cookie enables it to serve ads to our users based on previous visits to our site and other sites on the Internet.\nUsers may opt-out of the use of the DART cookie by visiting the Google Ad and Content Network privacy policy.";
  static const WEHAVE_WE_ = "We, along with third-party vendors such as Google use first-party cookies (such as the Google Analytics cookies) and third-party cookies (such as the DoubleClick cookie) or other third-party identifiers together to compile data regarding user interactions with ad impressions and other ad service functions as they relate to our website.";
  static const OPTINGOUT_USERS = "Users can set preferences for how Google advertises to you using the Google Ad Settings page. Alternatively, you can opt out by visiting the Network Advertising Initiative Opt Out page or by using the Google Analytics Opt Out Browser add on.";
}