class TermsAndConditionsTextos
{
  static const TERMS = "By accessing the website at asicminervalue.com, you are agreeing to be bound by these terms of service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this website are protected by applicable copyright and trademark law.";
  static const USELICENSE_PERMISSION = "Permission is granted to temporarily download one copy of the materials (information or software) on ASIC Miner Value’s website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:";
  static const USELICENSE_MODIFY = "Modify or copy the materials";
  static const USELICENSE_USE_THE_MATERIAL = "Use the materials for any commercial purpose, or for any public display (commercial or non-commercial)";
  static const USELICENSE_ATTEMP = "Attempt to decompile or reverse engineer any software contained on ASIC Miner Value’s website";
  static const USELICENSE_REMOVE = "Remove any copyright or other proprietary notations from the materials; or";
  static const USELICENSE_TRANSFER = "Transfer the materials to another person or “mirror” the materials on any other server.";
  static const USELICENSE_THIS_LICENSE_SHALL = "This license shall automatically terminate if you violate any of these restrictions and may be terminated by ASIC Miner Value at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.";
  static const DISCLAIMER_THE_MATERIALS = "The materials on ASIC Miner Value’s website are provided on an ‘as is’ basis. ASIC Miner Value makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.";
  static const DISCLAIMER_FURTHER = "Further, ASIC Miner Value does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its website or otherwise relating to such materials or on any sites linked to this site.";
  static const LIMITATIONS = "In no event shall ASIC Miner Value or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on ASIC Miner Value’s website, even if ASIC Miner Value or a ASIC Miner Value authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability\nfor consequential or incidental damages, these limitations may not apply to you.";
  static const ACCURACY = "The materials appearing on ASIC Miner Value website could include technical, typographical, or photographic errors. ASIC Miner Value does not warrant that any of the materials on its website are accurate, complete or current. ASIC Miner Value may make changes to the materials contained on its website at any time without notice. However ASIC Miner Value does not make any commitment to update the materials.";
  static const API = "APIs are provided as-is, for personnal use, do not reproduce this website, do not grab data, any business use must be allowed by contract, contact us.";
  static const LINKS = "ASIC Miner Value has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by ASIC Miner Value of the site. Use of any such linked website is at the user’s own risk.";
  static const MODIFICATIONS = "ASIC Miner Value may revise these terms of service for its website at any time without notice. By using this website you are agreeing to be bound by the then current version of these terms of service.";
  static const GOVERNING = "These terms and conditions are governed by and construed in accordance with the laws of France and you irrevocably submit to the exclusive jurisdiction of the courts in this country.";
}